### ISSUE TITLE
chap09 / recipe06 "make test" fails on mageia v7 x86-64

### ISSUE THREAD

**Issue by shlomif** [bast/cmake-recipes#334]
See:

```
shlomif@telaviv1:~/Download/Docs/Books/cmake/cmake-recipes/chapter-09/recipe-06/cxx-example/b2$ cmake ..
-- Configuring done
-- Generating done
-- Build files have been written to: /home/shlomif/Download/Docs/Books/cmake/cmake-recipes/chapter-09/recipe-06/cxx-example/b2
shlomif@telaviv1:~/Download/Docs/Books/cmake/cmake-recipes/chapter-09/recipe-06/cxx-example/b2$ make 
[100%] Built target account
shlomif@telaviv1:~/Download/Docs/Books/cmake/cmake-recipes/chapter-09/recipe-06/cxx-example/b2$ make test
Running tests...
Test project /home/shlomif/Download/Docs/Books/cmake/cmake-recipes/chapter-09/recipe-06/cxx-example/b2
    Start 1: python_test
1/1 Test #1: python_test ......................***Failed    0.05 sec

0% tests passed, 1 tests failed out of 1

Total Test time (real) =   0.05 sec

The following tests FAILED:
          1 - python_test (Failed)
Errors while running CTest
make: *** [Makefile:73: test] Error 8
shlomif@telaviv1:~/Download/Docs/Books/cmake/cmake-recipes/chapter-09/recipe-06/cxx-example/b2$ 

```

**Comment by bast** [comment]
Thanks for reporting! From the error it is not easy to see what is wrong. Can you post the output of:
```
$ cat Testing/Temporary/LastTest.log
```

What is probably wrong is missing CFFI Python package. But it could be something else.

**Comment by shlomif** [comment]
here it is:

```
shlomif@telaviv1:~/Download/Docs/Books/cmake/cmake-recipes/chapter-09/recipe-06/cxx-example/b2$ cat Testing/Temporary/LastTest.log
Start testing: May 07 14:00 IDT
----------------------------------------------------------
1/1 Testing: python_test
1/1 Test: python_test
Command: "/usr/bin/python" "/home/shlomif/Download/Docs/Books/cmake/cmake-recipes/chapter-09/recipe-06/cxx-example/account/test.py"
Directory: /home/shlomif/Download/Docs/Books/cmake/cmake-recipes/chapter-09/recipe-06/cxx-example/b2
"python_test" start time: May 07 14:00 IDT
Output:
----------------------------------------------------------
Traceback (most recent call last):
  File "/home/shlomif/Download/Docs/Books/cmake/cmake-recipes/chapter-09/recipe-06/cxx-example/account/test.py", line 1, in <module>
    import account
  File "/home/shlomif/Download/Docs/Books/cmake/cmake-recipes/chapter-09/recipe-06/cxx-example/account/__init__.py", line 1, in <module>
    from .cffi_helpers import get_lib_handle
  File "/home/shlomif/Download/Docs/Books/cmake/cmake-recipes/chapter-09/recipe-06/cxx-example/account/cffi_helpers.py", line 4, in <module>
    from cffi import FFI
ImportError: No module named cffi
<end of output>
Test time =   0.05 sec
----------------------------------------------------------
Test Failed.
"python_test" end time: May 07 14:00 IDT
"python_test" time elapsed: 00:00:00
----------------------------------------------------------

shlomif@telaviv1:~/Download/Docs/Books/cmake/cmake-recipes/chapter-09/recipe-06/cxx-example/b2$ 
```

**Comment by shlomif** [comment]
after installing python2-cffi, I am getting this:

```
shlomif@telaviv1:~/Download/Docs/Books/cmake/cmake-recipes/chapter-09/recipe-06/cxx-example/b2$ cat Testing/Temporary/LastTest.log
Start testing: May 07 18:59 IDT
----------------------------------------------------------
1/1 Testing: python_test
1/1 Test: python_test
Command: "/usr/bin/python" "/home/shlomif/Download/Docs/Books/cmake/cmake-recipes/chapter-09/recipe-06/cxx-example/account/test.py"
Directory: /home/shlomif/Download/Docs/Books/cmake/cmake-recipes/chapter-09/recipe-06/cxx-example/b2
"python_test" start time: May 07 18:59 IDT
Output:
----------------------------------------------------------
Traceback (most recent call last):
  File "/home/shlomif/Download/Docs/Books/cmake/cmake-recipes/chapter-09/recipe-06/cxx-example/account/test.py", line 1, in <module>
    import account
  File "/home/shlomif/Download/Docs/Books/cmake/cmake-recipes/chapter-09/recipe-06/cxx-example/account/__init__.py", line 29, in <module>
    _include_dir)
  File "/home/shlomif/Download/Docs/Books/cmake/cmake-recipes/chapter-09/recipe-06/cxx-example/account/cffi_helpers.py", line 22, in get_lib_handle
    lib = ffi.dlopen(lib_file_name)
  File "/usr/lib64/python2.7/site-packages/cffi/api.py", line 141, in dlopen
    lib, function_cache = _make_ffi_library(self, name, flags)
  File "/usr/lib64/python2.7/site-packages/cffi/api.py", line 795, in _make_ffi_library
    backendlib = _load_backend_lib(backend, libname, flags)
  File "/usr/lib64/python2.7/site-packages/cffi/api.py", line 790, in _load_backend_lib
    raise OSError(msg)
OSError: cannot load library /home/shlomif/Download/Docs/Books/cmake/cmake-recipes/chapter-09/recipe-06/cxx-example/b2/lib/libaccount.so: /home/shlomif/Download/Docs/Books/cmake/cmake-recipes/chapter-09/recipe-06/cxx-example/b2/lib/libaccount.so: cannot open shared object file: No such file or directory.  Additionally, ctypes.util.find_library() did not manage to locate a library called '/home/shlomif/Download/Docs/Books/cmake/cmake-recipes/chapter-09/recipe-06/cxx-example/b2/lib/libaccount.so'
<end of output>
Test time =   1.07 sec
----------------------------------------------------------
Test Failed.
"python_test" end time: May 07 18:59 IDT
"python_test" time elapsed: 00:00:01
----------------------------------------------------------

End testing: May 07 18:59 IDT
shlomif@telaviv1:~/Download/Docs/Books/cmake/cmake-recipes/chapter-09/recipe-06/cxx-example/b2$ ls lib64/
libaccount.so
shlomif@telaviv1:~/Download/Docs/Books/cmake/cmake-recipes/chapter-09/recipe-06/cxx-example/b2$ 
```

**Comment by robertodr** [comment]
It's [this line](https://github.com/bast/cmake-recipes/blob/master/chapter-09/recipe-06/cxx-example/CMakeLists.txt#L30). Instead of pointing to `lib` it should point to `lib64` and that can be adjusted by pulling [these lines](https://github.com/bast/cmake-recipes/blob/master/chapter-09/recipe-06/cxx-example/account/CMakeLists.txt#L1-L3) one layer up (from `account` to the root directory) and using `CMAKE_INSTALL_LIBDIR` instead of bare `lib`.

**Comment by bast** [comment]
Thanks! Yes, the bare "lib" was bad.
